name: Docker Image CI

on:
  schedule:
    # Run the workflow every Monday at 00:00 UTC
    - cron: '0 0 * * MON'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile.pihole --tag pihole:$(date +%s)
