name: Build Pi-hole Docker Image

on:
  schedule:
    # Run the workflow every Monday at 00:00 UTC
    - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access the Dockerfile
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image using the Dockerfile at the specified path
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:pihole-latest -f docker/Dockerfile.pihole .

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:pihole-latest
