name: Build Pi-hole Docker Image

on:
  schedule:
    # Run the workflow every Monday at 00:00 UTC
    - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access the Dockerfile
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image using the Dockerfile in the "docker" folder
      - name: Build Docker image
        run: |
          docker buildx build \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:main \
            -f docker/Dockerfile.pihole \
            --push .
